[package]
name = "rust-cuarenta"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-ws = "0.3.0"
actix-session = { version = "0.10.1", features = ["cookie-session"] }
serde = { version = "1.0.210", features = ["derive"] }
rand = "0.8.5"
lazy_static = "1.5.0"
